### ISSUE TITLE
No Result File for the python implementation

### ISSUE THREAD

**Issue by PJthunder** [THUDM/ProNE#3]
Thank you for providing the implementation of IJCAI paper.
I have tried your python implementation but it fails to write any files (using the PPI dataset as an example). Some temp running results were printed. But not for the final result.

I may have a try of the c++ implementation and see how everything is going!

**Comment by PJthunder** [comment]
Just found that your comment out the two lines for saving the numpy matrix. I think it's better to uncomment them.

For the C implementation, I accidentally do not have libboost in my new virtual machine, so maybe include that in the dependency package in the future. Also, need to `mkdir emb` before generating the results for the examples. Otherwise there will be "segmentation fault". Just add some small correction will make it better.

**Comment by lykeven** [comment]
Thanks a lot for the useful suggestion!
Output lines are uncommented,  boost and `mkdir emb` are included in README.
