### ISSUE TITLE
Is it normal that python implementation is faster than the c implementation?

### ISSUE THREAD

**Issue by PJthunder** [THUDM/ProNE#5]
I have used the youtube link graph as an example to test the reliability of the model. The python version of implementation lasts only 3-5 mins. But the c implementation, which should be parallelized,  is much slower. Is it normal?

**Comment by lykeven** [comment]
Well, running time is different according to the running enviorment.  
We conducted all experiments on a Red Hat server with Intel Xeon(R) 32 core CPU E5-4650 (2.70GHz) and 1T RAM.  The running time of python version on youtube is 10-13 mins while c++ implementation lasts 4-5 mins under all following optimization options.

Compiler option [`-O3`](https://gcc.gnu.org/onlinedocs/gcc-4.1.1/gcc/Optimize-Options.html), Openmp support [`-fopenmp`](http://eigen.tuxfamily.org/dox/TopicMultiThreading.html), [MKL link](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor/), `-mavx` or `-mfma` can be used based on Cpu architecture.

We recommend you to use the python version, which is more stable and effective while the c++ implementation is still optimizing.
