### ISSUE TITLE
Indexing of Nodes

### ISSUE THREAD

**Issue by PJthunder** [THUDM/ProNE#6]
The input file of this model should be continuous series of integers starting from 0? Like 0,1,2,3,4,5...
What if the node numbers are like 0,2,5,8,7,13,3. Should I reindex the node numbers?

Also, for the npy dump files generated by the python implementation, there is no index for each line. So can I assume that the first line embeds node 0, the second line embeds node1, and so on?

**Comment by lykeven** [comment]
Yes. For now, the node numbers should be integers starting from 0. In your case, reindexing is required.  For output embedding, the `k`-th line embeds node `k.`

**Comment by PJthunder** [comment]
Cool. Thanks for your response!
