### ISSUE TITLE
带权重有向图？

### ISSUE THREAD

**Issue by wangzhegeek** [THUDM/ProNE#9]
这个算法可以用于带权重的有向图吗？

**Comment by lykeven** [comment]
可以的，理论上ProNE算法处理的是邻接矩阵，输入图是有向有权的话，可以直接体现在邻接矩阵里。
但现在的使用的几个实验数据都是无向无权图，所以在数据的输入代码部分进行了简化处理。
要你想处理有向有权图，只要把输入部分改一下就可以了，后续的操作都兼容。

**Comment by wangzhegeek** [comment]
嗯嗯我看到了，挺好改的。那你们有没有测过把实验数据改成有权有向的结果有没有比无权无向的好

**Comment by wangzhegeek** [comment]
还有如果图中个别边的权重很大，剩下的边权重都很小，这会对模型的结果造成什么影响

**Comment by lykeven** [comment]
1.实验数据怎么能改。。一样的数据，结果肯定是一样的。
2.如果图中个别边的权重很大，剩下的边权重都很小，确实会对模型造成影响，但是相比于其他算法，影响不会很大。因为我们的算法里，稀疏矩阵分解的哪一步构造的矩阵就是对边进行了重权重，即无向无权图的边权重0/1转成0/float。

**Comment by wangzhegeek** [comment]
关于实验数据，数据肯定不能改，我的意思是有没有在一些有向带权重的数据上和别的方法比较下，效果如何
